import os
from dotenv import load_dotenv

# Load environment variables from a .env file
load_dotenv()

# --- Database and FAISS Index Paths ---
# The base directory for storing user-specific data when in "isolated" LTM mode.
USER_DATA_DIR = "user_data"
# Default path for the SQLite database file. Can be overridden by the ACE_DB_PATH env var.
DB_PATH = os.environ.get("ACE_DB_PATH", "ace_memory.db")
# Default path for the FAISS index file. Can be overridden by the ACE_FAISS_INDEX_PATH env var.
FAISS_INDEX_PATH = os.environ.get("ACE_FAISS_INDEX_PATH", "ace_memory.faiss")

# --- LLM Configuration ---
# The name of the language model to be used. Can be overridden by the LLM_MODEL env var.
MODEL_NAME = os.environ.get("LLM_MODEL", "gpt-oss-120b")
# The base URL for the LLM API. Can be overridden by the LLM_BASE_URL env var.
BASE_URL = os.environ.get("LLM_BASE_URL", "https://api.ai.sakura.ad.jp/v1/")
# The temperature setting for the LLM, controlling randomness. Can be overridden by the LLM_TEMPERATURE env var.
LLM_TEMPERATURE = float(os.environ.get("LLM_TEMPERATURE", "0.0"))
# The API key for the LLM. It first checks for LLM_API_KEY, then falls back to SAKURA_API_KEY for backward compatibility.
OPENAI_API_KEY = os.environ.get("LLM_API_KEY") or os.environ.get("SAKURA_API_KEY", "dummy_key")

# --- ACE Memory Configuration ---
# The distance metric for FAISS index ('l2' for L2 distance, 'cosine' for cosine similarity). Can be overridden by ACE_DISTANCE_METRIC.
DISTANCE_METRIC = os.environ.get('ACE_DISTANCE_METRIC', 'l2').lower()
# Default distance threshold for vector search. It's adjusted based on the DISTANCE_METRIC.
DEFAULT_THRESHOLD = 0.7 if DISTANCE_METRIC == 'cosine' else 1.8
# The actual distance threshold used for filtering search results. Can be overridden by ACE_DISTANCE_THRESHOLD.
DISTANCE_THRESHOLD = float(os.environ.get('ACE_DISTANCE_THRESHOLD', str(DEFAULT_THRESHOLD)))
# The name of the sentence transformer model to use for embeddings. Can be overridden by ACE_EMBEDDING_MODEL.
ENCODER_NAME = os.environ.get('ACE_EMBEDDING_MODEL', 'all-MiniLM-L6-v2')
# The dimension of the embeddings generated by the model. Can be overridden by ACE_EMBEDDING_DIMENSION.
EMBEDDING_DIMENSION = int(os.environ.get('ACE_EMBEDDING_DIMENSION', '384'))
# A flag to determine if language-specific prompts should be used (e.g., for Japanese). Set by the ACE_LANG env var.
ACE_LANG = os.environ.get("ACE_LANG", "en")
